### ISSUE TITLE
Book - Computer Graphics In Python

### ISSUE THREAD

**Issue by stuaxo** [rjopek/cairo-list#1]
We should put the book Computer Graphics In Python by Martin McBride in the list.

I finally got round to reading this and it filled in some gaps I had in cairo despite using it on occasion for more than ten years.

https://leanpub.com/computergraphicsinpython

Maybe @martinmcbride can chip in if the link above is the best one.

**Comment by rjopek** [comment]
Of course yes, please add, many thanks.

**Comment by martinmcbride** [comment]
Thanks for reading my book, I hope found it useful.

The link you provided is the best link for the book.

**Comment by rjopek** [comment]
I suggest creating a new category Books?

**Comment by stuaxo** [comment]
@rjopek will do.

@martinmcbride I haven't had the free time to for it to be useful since I only read it last night (after buying it a while back) - but it definitely will in Shoebot, or it's successor.

It really filled in gaps in Patterns, Clipping and Gradients.   In an ideal world I'd have some funding come your way + this be part of the official docs.

**Comment by stuaxo** [comment]
Cheers for the merge.
